import { definePrompts } from "./types";

export const availablePrompts = definePrompts({
  together_we_could: { text: "Together we could" },
  geek_out_on: { text: "I geek out on" },
  go_crazy_for: { text: "I go crazy for" },
  what_if_told_you: { text: "What if I told you that" },
  one_thing_know: { text: "The one thing you should know about me is" },
  same_page_about: { text: "Let's make sure we're on the same page about" },
  want_someone_who: { text: "I want someone who" },
  dorkiest_thing: { text: "The dorkiest thing about me is" },
  wont_shut_up: { text: "I won't shut up about" },
  this_year_want: { text: "This year, I really want to" },
  life_goal: { text: "A life goal of mine" },
  same_type_weird: { text: "We're the same type of weird if" },
  leave_comment_if: { text: "You should leave a comment if" },
  looking_for: { text: "I'm looking for" },
  love_about_you: { text: "The one thing I'd love to know about you is" },
  non_negotiable: { text: "Something that's non-negotiable for me" },
  weirdest_gift: { text: "Weirdest gift I have given or received" },
  shower_thought: { text: "A shower thought I recently had" },
  all_i_ask: { text: "All I ask is that you" },
  biggest_risk: { text: "Biggest risk I've taken" },
  way_to_win: { text: "The way to win me over is" },
  unusual_skills: { text: "Unusual skills" },
  greatest_strength: { text: "My greatest strength" },
  pick_topic: { text: "I'll pick the topic if you start the conversation" },
  key_to_heart: { text: "The key to my heart is" },
  controversial_opinion: { text: "My most controversial opinion" },
  guess_about_me: { text: "Try to guess this about me" },
  brag_if: { text: "I'll brag about you to my friends if" },
  fall_for_you: { text: "I'll fall for you if" },
  get_along_if: { text: "We'll get along if" },
  weirdly_attracted: { text: "I'm weirdly attracted to" },
  quick_rant: { text: "A quick rant about" },
  bff_take: { text: "My BFF's take on why you should date me" },
  wind_down: { text: "I wind down by" },
  out_of_funk: { text: "I get myself out of a funk by" },
  relaxation_is: { text: "To me, relaxation is" },
  boundary: { text: "A boundary of mine" },
  need_advice: { text: "When I need advice, I go to" },
  dating_me_like: { text: "Dating me is like" },
  irrational_fear: { text: "My most irrational fear" },
  loving_wrong: { text: "If loving this is wrong, I don't want to be right" },
  bet_you_cant: { text: "I bet you can't" },
  recently_discovered: { text: "I recently discovered that" },
  convinced_that: { text: "I'm convinced that" },
  first_round: { text: "First round is on me if" },
  agree_disagree: { text: "Do you agree or disagree that" },
  debate_topic: { text: "Let's debate this topic" },
  biggest_date_fail: { text: "My biggest date fail" },
  never_have_i: { text: "Never have I ever" },
  best_dad_joke: { text: "My best Dad joke" },
  self_care_routine: { text: "My self-care routine is" },
  change_mind: { text: "Change my mind about" },
  not_go_out_if: { text: "You should not go out with me if" },
  typical_sunday: { text: "Typical Sunday" },
  simple_pleasures: { text: "My simple pleasures" },
  spontaneous_thing: { text: "Most spontaneous thing I've done" },
  therapy_taught: { text: "Therapy recently taught me" },
  therapist_say: { text: "My therapist would say I" },
  journal_entry: { text: "My last journal entry was about" },
  two_truths_lie: { text: "Two truths and a lie" },
  random_fact: { text: "A random fact I love is" },
  social_cause: { text: "A social cause I care about" },
  overshare: { text: "An overshare" },
  believe_it_or_not: { text: "Believe it or not, I" },
  surprising_fact: { text: "Fact about me that surprises people" },
  green_flags: { text: "Green flags I look for" },
  good_relationship: { text: "The hallmark of a good relationship is" },
  get_along_best: { text: "I get along best with people who" },
  take_pride: { text: "I take pride in" },
  finally_ready: { text: "I think I'm finally ready to" },
  travel_story: { text: "Best travel story" },
  dont_hate_me: { text: "Don't hate me if" },
  teach_me: { text: "Teach me something about" },
  best_spot: { text: "I know the best spot in town for" },
  worst_idea: { text: "Worst idea I've ever had" },
  never_do_again: { text: "One thing I'll never do again" },
  pronounce_name: { text: "How to pronounce my name" },
  ask_me_out: { text: "The best way to ask me out is" },
  order_for_table: { text: "What I order for the table" },
  love_language: { text: "My love language is" },
  travel_tips: { text: "Give me travel tips for" },
  connect_community: { text: "I connect to my community by" },
  tell_younger_self: {
    text: "I wish I could tell the younger version of myself",
  },
  proudest_when: { text: "I feel proudest of who I am when" },
  life_soundtrack: { text: "Apparently, my life's soundtrack is" },
  guess_song: { text: "Guess the song" },
  feel_supported: { text: "I feel most supported when" },
  hype_myself: { text: "I hype myself up by" },
  wish_people_knew: { text: "I wish more people knew" },
  setup_punchline: {
    text: "I'll give you the set up, you guess the punchline",
  },
  celebrity_impression: { text: "My best celebrity impression" },
  cry_car_song: { text: "My cry-in-the-car song is" },
  favorite_movie_line: { text: "My favorite line from a movie" },
  friends_advice: { text: "My friends ask me for advice about" },
  happy_place: { text: "My happy place" },
  musical_talent: { text: "Proof I have musical talent" },
  saying_hi_languages: { text: 'Saying "Hi!" in as many languages I know' },
});
